name: BP_Health
description: A Flutter health app for blood pressure measurement and monitoring. 
version: 1.0.0+1

environment:
  sdk: 3.9.2

dependencies:
  flutter:
    sdk: flutter

provider: ^6.1.2 # For state managements

http: ^1.2.0 # For HTTP/HTTPS requests

web_socket_channel: ^2.4.0 # For websocket support

intl: ^0.19.0 # For date/timestamp formatting

flutter_material_pickers: ^5.1.0 # potential modern UI components

fl_chart: ^0.69.0 # For charts and graphs

cupertino_icons: ^1.0.8 # SDK libraries for flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/ # For logos/icons
    - assets/icons/

